name: Clippy Fix

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:

jobs:
  clippy-fix:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run cargo clippy with fix
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: clippy
         
    - name: Run cargo clippy with fix
      run: cargo clippy --fix --allow-dirty --all-targets --broken-code
      continue-on-error: true

    - name: Capture warnings and errors
      run: |
        echo "Warnings and Errors:"
        cargo clippy -- --message-format=short
#        cargo clippy -- --message-format=short | tee clippy-warnings.txt

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Apply Clippy suggestions" || echo "No changes to commit."

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: Apply Clippy suggestions
        branch: clippy-fixes
        title: "Clippy Fixes"
        body: "This PR contains changes from running cargo clippy --fix"
        labels: clippy, review

#    - name: Upload Clippy Logs
#      uses: actions/upload-artifact@v4
#      with:
#        name: clippy-warnings
#        path: clippy-warnings.txt
        
