name: "Auto-merge Dependabot minor updates"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]' && contains(github.event.pull_request.title, 'minor')
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Auto-merge Dependabot minor updates"
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --squash --admin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
